services:

  mongo-express:
    container_name: express
    image: mongo-express:1.0-20-alpine3.19
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - mongoexpress-network
  
  seeder:
      container_name: seeder
      build:
        context: .
        dockerfile: Dockerfile-seeder
      restart: 'no'
      depends_on:
        - mongodb
      environment:
        MONGODB_URI: mongodb://admin:secret@mongodb:27017 
      networks:
        - mongo-network