version: '3.8'  

services:
  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
      MONGODB_URI: mongodb://admin:secret@mongodb:27017
      REDIS_URI: redis://redis:6379
      ENABLE_WRITING_HANDLERS: 'false'
    networks:
      - mongo-network
      - redis-network
      - mongoexpress-network
    depends_on:
      - mongodb
      - redis

  mongodb:
    container_name: mongodb
    image: mongo:8.0-rc
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - '27017:27017'
    networks: 
      - mongo-network
      - mongoexpress-network
    volumes:
      - ./data:/data/db 

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    networks:
      - redis-network

networks: 
  mongo-network:
  redis-network:
  mongoexpress-network:
